export type GitChangeStatus = 'added' | 'modified' | 'deleted' | 'renamed';

export interface DiffLine {
  type: 'add' | 'delete' | 'context';
  lineNumber?: number;
  content: string;
}

export interface GitChange {
  id: string;
  path: string;
  name: string;
  status: GitChangeStatus;
  oldPath?: string; // For renamed files
  additions?: number;
  deletions?: number;
  diff?: DiffLine[];
}

export interface GitCommit {
  id: string;
  hash: string;
  message: string;
  author: string;
  date: string;
  fileChanges: string[]; // IDs of GitChange items
  isAgent?: boolean; // Whether this commit was made by an MCP agent
  agentName?: string; // Name of the agent if isAgent is true
  branch: 'feature' | 'base';
}

export interface GitBranchInfo {
  currentBranch: string;
  baseBranch: string;
  changes: GitChange[];
  commits: GitCommit[];
  commitsBehind: number;
  commitsAhead: number;
  baseBranchChanges: GitChange[];
  branchPointDate?: string;
}

export const mockGitChanges: GitBranchInfo = {
  currentBranch: 'feature/documentation-updates',
  baseBranch: 'main',
  commitsBehind: 3,
  commitsAhead: 5,
  changes: [
    {
      id: 'change-1',
      path: '/docs/architecture/system-design.md',
      name: 'system-design.md',
      status: 'added',
      additions: 145,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: '# System Design' },
        { type: 'add', lineNumber: 2, content: '' },
        { type: 'add', lineNumber: 3, content: '## Overview' },
        { type: 'add', lineNumber: 4, content: '' },
        { type: 'add', lineNumber: 5, content: 'The Stash MCP system is built on a modular architecture' },
        { type: 'add', lineNumber: 6, content: 'that separates concerns into distinct layers.' },
        { type: 'add', lineNumber: 7, content: '' },
        { type: 'add', lineNumber: 8, content: '## Components' },
        { type: 'add', lineNumber: 9, content: '' },
        { type: 'add', lineNumber: 10, content: '### Content Server' },
        { type: 'add', lineNumber: 11, content: 'Handles document storage and retrieval via MCP protocol.' },
        { type: 'add', lineNumber: 12, content: '' },
        { type: 'add', lineNumber: 13, content: '### Auth Layer' },
        { type: 'add', lineNumber: 14, content: 'OAuth 2.0 and API key authentication for server access.' },
        { type: 'add', lineNumber: 15, content: '' },
        { type: 'add', lineNumber: 16, content: '### Virtual Content Roots' },
        { type: 'add', lineNumber: 17, content: 'Mounted directories with configurable R/RW permissions.' },
        { type: 'add', lineNumber: 18, content: '' },
        { type: 'add', lineNumber: 19, content: '## Architecture Diagram' },
        { type: 'add', lineNumber: 20, content: '' },
        { type: 'add', lineNumber: 21, content: '```' },
        { type: 'add', lineNumber: 22, content: '┌─────────────┐' },
        { type: 'add', lineNumber: 23, content: '│   Client    │' },
        { type: 'add', lineNumber: 24, content: '└──────┬──────┘' },
        { type: 'add', lineNumber: 25, content: '       │' },
        { type: 'add', lineNumber: 26, content: '       ▼' },
        { type: 'add', lineNumber: 27, content: '┌─────────────┐' },
        { type: 'add', lineNumber: 28, content: '│  MCP Server │' },
        { type: 'add', lineNumber: 29, content: '└──────┬──────┘' },
        { type: 'add', lineNumber: 30, content: '       │' },
        { type: 'add', lineNumber: 31, content: '       ▼' },
        { type: 'add', lineNumber: 32, content: '┌─────────────┐' },
        { type: 'add', lineNumber: 33, content: '│  Storage    │' },
        { type: 'add', lineNumber: 34, content: '└─────────────┘' },
        { type: 'add', lineNumber: 35, content: '```' },
      ],
    },
    {
      id: 'change-2',
      path: '/docs/api/endpoints.md',
      name: 'endpoints.md',
      status: 'modified',
      additions: 23,
      deletions: 8,
      diff: [
        { type: 'context', lineNumber: 10, content: '## Authentication' },
        { type: 'context', lineNumber: 11, content: '' },
        { type: 'delete', lineNumber: 12, content: 'Use basic auth headers for all requests.' },
        { type: 'delete', lineNumber: 13, content: 'Authorization: Basic <token>' },
        { type: 'add', lineNumber: 12, content: 'Use OAuth 2.0 bearer tokens for all requests.' },
        { type: 'add', lineNumber: 13, content: 'Authorization: Bearer <access_token>' },
        { type: 'add', lineNumber: 14, content: '' },
        { type: 'add', lineNumber: 15, content: 'Alternatively, use API keys via the X-API-Key header.' },
        { type: 'context', lineNumber: 16, content: '' },
        { type: 'context', lineNumber: 17, content: '## Endpoints' },
        { type: 'context', lineNumber: 18, content: '' },
        { type: 'delete', lineNumber: 19, content: '### GET /api/documents' },
        { type: 'add', lineNumber: 19, content: '### GET /api/v2/documents' },
        { type: 'context', lineNumber: 20, content: 'Returns a list of all documents.' },
        { type: 'context', lineNumber: 21, content: '' },
        { type: 'delete', lineNumber: 22, content: '### POST /api/documents' },
        { type: 'add', lineNumber: 22, content: '### POST /api/v2/documents' },
        { type: 'add', lineNumber: 23, content: '' },
        { type: 'add', lineNumber: 24, content: '### GET /api/v2/documents/:id/diff' },
        { type: 'add', lineNumber: 25, content: 'Returns the diff for a specific document version.' },
        { type: 'context', lineNumber: 26, content: '' },
      ],
    },
    {
      id: 'change-3',
      path: '/docs/guides/getting-started.md',
      name: 'getting-started.md',
      status: 'modified',
      additions: 67,
      deletions: 12,
      diff: [
        { type: 'context', lineNumber: 1, content: '# Getting Started' },
        { type: 'context', lineNumber: 2, content: '' },
        { type: 'delete', lineNumber: 3, content: '## Installation' },
        { type: 'delete', lineNumber: 4, content: 'Download the binary from the releases page.' },
        { type: 'add', lineNumber: 3, content: '## Quick Start' },
        { type: 'add', lineNumber: 4, content: '' },
        { type: 'add', lineNumber: 5, content: '### Prerequisites' },
        { type: 'add', lineNumber: 6, content: '- Node.js 18+' },
        { type: 'add', lineNumber: 7, content: '- Docker (optional)' },
        { type: 'add', lineNumber: 8, content: '' },
        { type: 'add', lineNumber: 9, content: '### Installation' },
        { type: 'add', lineNumber: 10, content: '```bash' },
        { type: 'add', lineNumber: 11, content: 'npm install -g @stash/mcp-server' },
        { type: 'add', lineNumber: 12, content: 'stash init' },
        { type: 'add', lineNumber: 13, content: '```' },
        { type: 'context', lineNumber: 14, content: '' },
        { type: 'context', lineNumber: 15, content: '## Configuration' },
        { type: 'delete', lineNumber: 16, content: 'Edit the config file manually.' },
        { type: 'add', lineNumber: 16, content: 'Run `stash config` to open the interactive configurator.' },
        { type: 'add', lineNumber: 17, content: '' },
        { type: 'add', lineNumber: 18, content: '## First Steps' },
        { type: 'add', lineNumber: 19, content: '' },
        { type: 'add', lineNumber: 20, content: '1. Create a content root' },
        { type: 'add', lineNumber: 21, content: '2. Set up authentication' },
        { type: 'add', lineNumber: 22, content: '3. Start the server' },
      ],
    },
    {
      id: 'change-4',
      path: '/docs/reference/configuration.md',
      name: 'configuration.md',
      status: 'modified',
      additions: 34,
      deletions: 5,
      diff: [
        { type: 'context', lineNumber: 8, content: '## Server Settings' },
        { type: 'context', lineNumber: 9, content: '' },
        { type: 'delete', lineNumber: 10, content: 'port: 3000' },
        { type: 'add', lineNumber: 10, content: 'port: 8080  # Changed default port' },
        { type: 'add', lineNumber: 11, content: 'host: 0.0.0.0' },
        { type: 'context', lineNumber: 12, content: '' },
        { type: 'context', lineNumber: 13, content: '## Content Roots' },
        { type: 'context', lineNumber: 14, content: '' },
        { type: 'delete', lineNumber: 15, content: 'roots:' },
        { type: 'delete', lineNumber: 16, content: '  - path: /data' },
        { type: 'add', lineNumber: 15, content: 'content_roots:' },
        { type: 'add', lineNumber: 16, content: '  - name: "Primary Docs"' },
        { type: 'add', lineNumber: 17, content: '    path: /data/docs' },
        { type: 'add', lineNumber: 18, content: '    permissions: rw' },
        { type: 'add', lineNumber: 19, content: '  - name: "Archives"' },
        { type: 'add', lineNumber: 20, content: '    path: /data/archive' },
        { type: 'add', lineNumber: 21, content: '    permissions: r' },
        { type: 'context', lineNumber: 22, content: '' },
      ],
    },
    {
      id: 'change-5',
      path: '/docs/old-readme.md',
      name: 'old-readme.md',
      status: 'deleted',
      additions: 0,
      deletions: 89,
      diff: [
        { type: 'delete', lineNumber: 1, content: '# Old README' },
        { type: 'delete', lineNumber: 2, content: '' },
        { type: 'delete', lineNumber: 3, content: 'This file is no longer maintained.' },
        { type: 'delete', lineNumber: 4, content: 'Please refer to the new documentation structure.' },
        { type: 'delete', lineNumber: 5, content: '' },
        { type: 'delete', lineNumber: 6, content: '## Deprecated Sections' },
        { type: 'delete', lineNumber: 7, content: '' },
        { type: 'delete', lineNumber: 8, content: '- Installation (moved to getting-started.md)' },
        { type: 'delete', lineNumber: 9, content: '- API Reference (moved to api/endpoints.md)' },
        { type: 'delete', lineNumber: 10, content: '- Configuration (moved to reference/configuration.md)' },
      ],
    },
    {
      id: 'change-6',
      path: '/docs/deployment/docker.md',
      name: 'docker.md',
      status: 'added',
      additions: 78,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: '# Docker Deployment' },
        { type: 'add', lineNumber: 2, content: '' },
        { type: 'add', lineNumber: 3, content: '## Dockerfile' },
        { type: 'add', lineNumber: 4, content: '' },
        { type: 'add', lineNumber: 5, content: '```dockerfile' },
        { type: 'add', lineNumber: 6, content: 'FROM node:18-alpine' },
        { type: 'add', lineNumber: 7, content: 'WORKDIR /app' },
        { type: 'add', lineNumber: 8, content: 'COPY package*.json ./' },
        { type: 'add', lineNumber: 9, content: 'RUN npm ci --production' },
        { type: 'add', lineNumber: 10, content: 'COPY . .' },
        { type: 'add', lineNumber: 11, content: 'EXPOSE 8080' },
        { type: 'add', lineNumber: 12, content: 'CMD ["node", "server.js"]' },
        { type: 'add', lineNumber: 13, content: '```' },
        { type: 'add', lineNumber: 14, content: '' },
        { type: 'add', lineNumber: 15, content: '## Docker Compose' },
        { type: 'add', lineNumber: 16, content: '' },
        { type: 'add', lineNumber: 17, content: 'Use `docker-compose up -d` to start the stack.' },
        { type: 'add', lineNumber: 18, content: '' },
        { type: 'add', lineNumber: 19, content: '```yaml' },
        { type: 'add', lineNumber: 20, content: 'version: "3.8"' },
        { type: 'add', lineNumber: 21, content: 'services:' },
        { type: 'add', lineNumber: 22, content: '  stash:' },
        { type: 'add', lineNumber: 23, content: '    build: .' },
        { type: 'add', lineNumber: 24, content: '    ports:' },
        { type: 'add', lineNumber: 25, content: '      - "8080:8080"' },
        { type: 'add', lineNumber: 26, content: '```' },
      ],
    },
    {
      id: 'change-7',
      path: '/docs/changelog.md',
      name: 'CHANGELOG.md',
      status: 'renamed',
      oldPath: '/docs/changes.md',
      additions: 12,
      deletions: 3,
      diff: [
        { type: 'delete', lineNumber: 1, content: '# Changes' },
        { type: 'add', lineNumber: 1, content: '# Changelog' },
        { type: 'context', lineNumber: 2, content: '' },
        { type: 'add', lineNumber: 3, content: '## [2.0.0] - 2023-10-05' },
        { type: 'add', lineNumber: 4, content: '' },
        { type: 'add', lineNumber: 5, content: '### Breaking Changes' },
        { type: 'add', lineNumber: 6, content: '- API endpoints moved to /api/v2/' },
        { type: 'add', lineNumber: 7, content: '- Default port changed to 8080' },
        { type: 'add', lineNumber: 8, content: '' },
        { type: 'context', lineNumber: 9, content: '## [1.0.0] - 2023-09-01' },
        { type: 'context', lineNumber: 10, content: '' },
        { type: 'delete', lineNumber: 11, content: '- Initial version' },
        { type: 'add', lineNumber: 11, content: '- Initial release' },
      ],
    },
    {
      id: 'change-8',
      path: '/src/server/auth.ts',
      name: 'auth.ts',
      status: 'modified',
      additions: 45,
      deletions: 18,
      diff: [
        { type: 'context', lineNumber: 1, content: 'import { Request, Response } from "express";' },
        { type: 'delete', lineNumber: 2, content: 'import jwt from "jsonwebtoken";' },
        { type: 'add', lineNumber: 2, content: 'import { verify } from "jsonwebtoken";' },
        { type: 'add', lineNumber: 3, content: 'import { OAuth2Client } from "google-auth-library";' },
        { type: 'context', lineNumber: 4, content: '' },
        { type: 'add', lineNumber: 5, content: 'const oauthClient = new OAuth2Client(process.env.OAUTH_CLIENT_ID);' },
        { type: 'add', lineNumber: 6, content: '' },
        { type: 'context', lineNumber: 7, content: 'export async function authenticate(req: Request) {' },
        { type: 'delete', lineNumber: 8, content: '  const token = req.headers.authorization?.split(" ")[1];' },
        { type: 'delete', lineNumber: 9, content: '  if (!token) throw new Error("No token provided");' },
        { type: 'add', lineNumber: 8, content: '  const authHeader = req.headers.authorization;' },
        { type: 'add', lineNumber: 9, content: '  const apiKey = req.headers["x-api-key"];' },
        { type: 'add', lineNumber: 10, content: '' },
        { type: 'add', lineNumber: 11, content: '  // Try OAuth token first' },
        { type: 'add', lineNumber: 12, content: '  if (authHeader?.startsWith("Bearer ")) {' },
        { type: 'add', lineNumber: 13, content: '    const token = authHeader.split(" ")[1];' },
        { type: 'add', lineNumber: 14, content: '    return await verifyOAuthToken(token);' },
        { type: 'add', lineNumber: 15, content: '  }' },
        { type: 'add', lineNumber: 16, content: '' },
        { type: 'add', lineNumber: 17, content: '  // Fall back to API key' },
        { type: 'add', lineNumber: 18, content: '  if (apiKey) {' },
        { type: 'add', lineNumber: 19, content: '    return await verifyApiKey(apiKey as string);' },
        { type: 'add', lineNumber: 20, content: '  }' },
        { type: 'add', lineNumber: 21, content: '' },
        { type: 'add', lineNumber: 22, content: '  throw new Error("No authentication provided");' },
        { type: 'context', lineNumber: 23, content: '}' },
      ],
    },
    {
      id: 'change-9',
      path: '/src/server/storage.ts',
      name: 'storage.ts',
      status: 'modified',
      additions: 28,
      deletions: 12,
      diff: [
        { type: 'context', lineNumber: 5, content: 'export class ContentStorage {' },
        { type: 'delete', lineNumber: 6, content: '  private rootPath: string;' },
        { type: 'add', lineNumber: 6, content: '  private contentRoots: ContentRoot[];' },
        { type: 'context', lineNumber: 7, content: '' },
        { type: 'delete', lineNumber: 8, content: '  constructor(rootPath: string) {' },
        { type: 'delete', lineNumber: 9, content: '    this.rootPath = rootPath;' },
        { type: 'add', lineNumber: 8, content: '  constructor(roots: ContentRoot[]) {' },
        { type: 'add', lineNumber: 9, content: '    this.contentRoots = roots;' },
        { type: 'context', lineNumber: 10, content: '  }' },
        { type: 'context', lineNumber: 11, content: '' },
        { type: 'add', lineNumber: 12, content: '  private findRoot(path: string): ContentRoot | undefined {' },
        { type: 'add', lineNumber: 13, content: '    return this.contentRoots.find(root => path.startsWith(root.path));' },
        { type: 'add', lineNumber: 14, content: '  }' },
        { type: 'add', lineNumber: 15, content: '' },
        { type: 'context', lineNumber: 16, content: '  async readFile(path: string): Promise<string> {' },
        { type: 'add', lineNumber: 17, content: '    const root = this.findRoot(path);' },
        { type: 'add', lineNumber: 18, content: '    if (!root) throw new Error("Path not in content root");' },
        { type: 'delete', lineNumber: 19, content: '    return fs.readFileSync(this.rootPath + path, "utf-8");' },
        { type: 'add', lineNumber: 19, content: '    return fs.readFileSync(path, "utf-8");' },
        { type: 'context', lineNumber: 20, content: '  }' },
      ],
    },
    {
      id: 'change-10',
      path: '/src/server/routes/api.ts',
      name: 'api.ts',
      status: 'modified',
      additions: 52,
      deletions: 24,
      diff: [
        { type: 'context', lineNumber: 1, content: 'import express from "express";' },
        { type: 'context', lineNumber: 2, content: 'import { authenticate } from "../auth";' },
        { type: 'context', lineNumber: 3, content: '' },
        { type: 'delete', lineNumber: 4, content: 'const router = express.Router();' },
        { type: 'add', lineNumber: 4, content: 'const v2Router = express.Router();' },
        { type: 'context', lineNumber: 5, content: '' },
        { type: 'delete', lineNumber: 6, content: 'router.get("/documents", async (req, res) => {' },
        { type: 'add', lineNumber: 6, content: 'v2Router.get("/documents", async (req, res) => {' },
        { type: 'context', lineNumber: 7, content: '  const user = await authenticate(req);' },
        { type: 'context', lineNumber: 8, content: '  // ... rest of handler' },
        { type: 'context', lineNumber: 9, content: '});' },
        { type: 'context', lineNumber: 10, content: '' },
        { type: 'add', lineNumber: 11, content: 'v2Router.get("/documents/:id/diff", async (req, res) => {' },
        { type: 'add', lineNumber: 12, content: '  const user = await authenticate(req);' },
        { type: 'add', lineNumber: 13, content: '  const { id } = req.params;' },
        { type: 'add', lineNumber: 14, content: '  const diff = await getDiff(id);' },
        { type: 'add', lineNumber: 15, content: '  res.json(diff);' },
        { type: 'add', lineNumber: 16, content: '});' },
        { type: 'add', lineNumber: 17, content: '' },
        { type: 'delete', lineNumber: 18, content: 'export default router;' },
        { type: 'add', lineNumber: 18, content: 'export { v2Router };' },
      ],
    },
    {
      id: 'change-11',
      path: '/tests/auth.test.ts',
      name: 'auth.test.ts',
      status: 'added',
      additions: 56,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: 'import { describe, it, expect } from "vitest";' },
        { type: 'add', lineNumber: 2, content: 'import { authenticate } from "../src/server/auth";' },
        { type: 'add', lineNumber: 3, content: '' },
        { type: 'add', lineNumber: 4, content: 'describe("Authentication", () => {' },
        { type: 'add', lineNumber: 5, content: '  it("should accept valid OAuth token", async () => {' },
        { type: 'add', lineNumber: 6, content: '    const req = {' },
        { type: 'add', lineNumber: 7, content: '      headers: { authorization: "Bearer valid-token" }' },
        { type: 'add', lineNumber: 8, content: '    };' },
        { type: 'add', lineNumber: 9, content: '    const result = await authenticate(req);' },
        { type: 'add', lineNumber: 10, content: '    expect(result).toBeDefined();' },
        { type: 'add', lineNumber: 11, content: '  });' },
        { type: 'add', lineNumber: 12, content: '' },
        { type: 'add', lineNumber: 13, content: '  it("should accept valid API key", async () => {' },
        { type: 'add', lineNumber: 14, content: '    const req = {' },
        { type: 'add', lineNumber: 15, content: '      headers: { "x-api-key": "valid-key" }' },
        { type: 'add', lineNumber: 16, content: '    };' },
        { type: 'add', lineNumber: 17, content: '    const result = await authenticate(req);' },
        { type: 'add', lineNumber: 18, content: '    expect(result).toBeDefined();' },
        { type: 'add', lineNumber: 19, content: '  });' },
        { type: 'add', lineNumber: 20, content: '' },
        { type: 'add', lineNumber: 21, content: '  it("should reject missing authentication", async () => {' },
        { type: 'add', lineNumber: 22, content: '    const req = { headers: {} };' },
        { type: 'add', lineNumber: 23, content: '    await expect(authenticate(req)).rejects.toThrow();' },
        { type: 'add', lineNumber: 24, content: '  });' },
        { type: 'add', lineNumber: 25, content: '});' },
      ],
    },
    {
      id: 'change-12',
      path: '/package.json',
      name: 'package.json',
      status: 'modified',
      additions: 8,
      deletions: 3,
      diff: [
        { type: 'context', lineNumber: 10, content: '  "dependencies": {' },
        { type: 'context', lineNumber: 11, content: '    "express": "^4.18.2",' },
        { type: 'delete', lineNumber: 12, content: '    "jsonwebtoken": "^9.0.0"' },
        { type: 'add', lineNumber: 12, content: '    "jsonwebtoken": "^9.0.0",' },
        { type: 'add', lineNumber: 13, content: '    "google-auth-library": "^9.0.0"' },
        { type: 'context', lineNumber: 14, content: '  },' },
        { type: 'context', lineNumber: 15, content: '  "devDependencies": {' },
        { type: 'add', lineNumber: 16, content: '    "vitest": "^1.0.0",' },
        { type: 'context', lineNumber: 17, content: '    "typescript": "^5.0.0"' },
        { type: 'context', lineNumber: 18, content: '  }' },
      ],
    },
    {
      id: 'change-13',
      path: '/config.example.yaml',
      name: 'config.example.yaml',
      status: 'added',
      additions: 24,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: '# Stash MCP Server Configuration' },
        { type: 'add', lineNumber: 2, content: '' },
        { type: 'add', lineNumber: 3, content: 'server:' },
        { type: 'add', lineNumber: 4, content: '  port: 8080' },
        { type: 'add', lineNumber: 5, content: '  host: 0.0.0.0' },
        { type: 'add', lineNumber: 6, content: '' },
        { type: 'add', lineNumber: 7, content: 'auth:' },
        { type: 'add', lineNumber: 8, content: '  oauth:' },
        { type: 'add', lineNumber: 9, content: '    enabled: true' },
        { type: 'add', lineNumber: 10, content: '    client_id: YOUR_CLIENT_ID' },
        { type: 'add', lineNumber: 11, content: '  api_keys:' },
        { type: 'add', lineNumber: 12, content: '    enabled: true' },
        { type: 'add', lineNumber: 13, content: '' },
        { type: 'add', lineNumber: 14, content: 'content_roots:' },
        { type: 'add', lineNumber: 15, content: '  - name: "Primary Docs"' },
        { type: 'add', lineNumber: 16, content: '    path: /data/docs' },
        { type: 'add', lineNumber: 17, content: '    permissions: rw' },
        { type: 'add', lineNumber: 18, content: '  - name: "Archives"' },
        { type: 'add', lineNumber: 19, content: '    path: /data/archive' },
        { type: 'add', lineNumber: 20, content: '    permissions: r' },
      ],
    },
  ],
  commits: [
    {
      id: 'commit-1',
      hash: 'abc123d',
      message: 'Add system design documentation',
      author: 'John Doe',
      date: '2023-10-01T12:34:56Z',
      fileChanges: ['change-1'],
      isAgent: true,
      agentName: 'Documentation Agent',
      branch: 'feature',
    },
    {
      id: 'commit-2',
      hash: 'def456e',
      message: 'Update API endpoints and configuration',
      author: 'Jane Smith',
      date: '2023-10-02T13:45:01Z',
      fileChanges: ['change-2', 'change-4'],
      isAgent: true,
      agentName: 'API Assistant',
      branch: 'feature',
    },
    {
      id: 'commit-3',
      hash: 'ghi789f',
      message: 'Update getting started guide',
      author: 'Alice Johnson',
      date: '2023-10-03T14:56:02Z',
      fileChanges: ['change-3'],
      branch: 'feature',
    },
    {
      id: 'commit-4',
      hash: 'jkl012g',
      message: 'Refactor authentication system',
      author: 'Bob Brown',
      date: '2023-10-04T09:22:15Z',
      fileChanges: ['change-8', 'change-9', 'change-10', 'change-11', 'change-12'],
      isAgent: false,
      branch: 'feature',
    },
    {
      id: 'commit-5',
      hash: 'mno345h',
      message: 'Clean up old documentation',
      author: 'Bob Brown',
      date: '2023-10-04T15:07:03Z',
      fileChanges: ['change-5'],
      branch: 'feature',
    },
    {
      id: 'commit-6',
      hash: 'pqr678i',
      message: 'Add Docker deployment and rename changelog',
      author: 'Charlie Davis',
      date: '2023-10-05T16:18:04Z',
      fileChanges: ['change-6', 'change-7'],
      isAgent: true,
      agentName: 'DevOps Agent',
      branch: 'feature',
    },
    {
      id: 'commit-7',
      hash: 'stu901j',
      message: 'Add example configuration file',
      author: 'Alice Johnson',
      date: '2023-10-06T10:30:22Z',
      fileChanges: ['change-13'],
      isAgent: false,
      branch: 'feature',
    },
    // Base branch commits (before the branch point)
    {
      id: 'commit-base-1',
      hash: 'f1a2b3c',
      message: 'Refactor server initialization and startup sequence',
      author: 'Eve Martinez',
      date: '2023-09-28T10:15:00Z',
      fileChanges: ['base-change-1', 'base-change-2'],
      branch: 'base',
    },
    {
      id: 'commit-base-2',
      hash: 'd4e5f6a',
      message: 'Add contributing guide and code of conduct',
      author: 'Frank Wilson',
      date: '2023-09-29T14:30:00Z',
      fileChanges: ['base-change-3'],
      branch: 'base',
    },
    {
      id: 'commit-base-3',
      hash: 'b7c8d9e',
      message: 'Bump dependencies and add request logging middleware',
      author: 'Grace Lee',
      date: '2023-09-30T09:45:00Z',
      fileChanges: ['base-change-4'],
      isAgent: true,
      agentName: 'Dependency Bot',
      branch: 'base',
    },
  ],
  branchPointDate: '2023-09-30T18:00:00Z',
  baseBranchChanges: [
    {
      id: 'base-change-1',
      path: '/src/server/index.ts',
      name: 'index.ts',
      status: 'modified',
      additions: 38,
      deletions: 22,
      diff: [
        { type: 'context', lineNumber: 1, content: 'import express from "express";' },
        { type: 'delete', lineNumber: 2, content: 'const app = express();' },
        { type: 'add', lineNumber: 2, content: 'import { createApp } from "./app";' },
        { type: 'add', lineNumber: 3, content: '' },
        { type: 'add', lineNumber: 4, content: 'async function main() {' },
        { type: 'add', lineNumber: 5, content: '  const app = await createApp();' },
        { type: 'context', lineNumber: 6, content: '' },
        { type: 'delete', lineNumber: 7, content: 'app.listen(3000, () => {' },
        { type: 'delete', lineNumber: 8, content: '  console.log("Server started");' },
        { type: 'add', lineNumber: 7, content: '  const port = process.env.PORT || 3000;' },
        { type: 'add', lineNumber: 8, content: '  app.listen(port, () => {' },
        { type: 'add', lineNumber: 9, content: '    console.log(`Server started on port ${port}`);' },
        { type: 'add', lineNumber: 10, content: '  });' },
        { type: 'add', lineNumber: 11, content: '}' },
        { type: 'add', lineNumber: 12, content: '' },
        { type: 'add', lineNumber: 13, content: 'main().catch(console.error);' },
      ],
    },
    {
      id: 'base-change-2',
      path: '/src/server/app.ts',
      name: 'app.ts',
      status: 'added',
      additions: 25,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: 'import express from "express";' },
        { type: 'add', lineNumber: 2, content: 'import cors from "cors";' },
        { type: 'add', lineNumber: 3, content: '' },
        { type: 'add', lineNumber: 4, content: 'export async function createApp() {' },
        { type: 'add', lineNumber: 5, content: '  const app = express();' },
        { type: 'add', lineNumber: 6, content: '  app.use(cors());' },
        { type: 'add', lineNumber: 7, content: '  app.use(express.json());' },
        { type: 'add', lineNumber: 8, content: '  return app;' },
        { type: 'add', lineNumber: 9, content: '}' },
      ],
    },
    {
      id: 'base-change-3',
      path: '/CONTRIBUTING.md',
      name: 'CONTRIBUTING.md',
      status: 'added',
      additions: 42,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: '# Contributing to Stash MCP' },
        { type: 'add', lineNumber: 2, content: '' },
        { type: 'add', lineNumber: 3, content: '## Getting Started' },
        { type: 'add', lineNumber: 4, content: '' },
        { type: 'add', lineNumber: 5, content: '1. Fork the repository' },
        { type: 'add', lineNumber: 6, content: '2. Create a feature branch' },
        { type: 'add', lineNumber: 7, content: '3. Make your changes' },
        { type: 'add', lineNumber: 8, content: '4. Submit a pull request' },
        { type: 'add', lineNumber: 9, content: '' },
        { type: 'add', lineNumber: 10, content: '## Code Style' },
        { type: 'add', lineNumber: 11, content: '' },
        { type: 'add', lineNumber: 12, content: 'We use ESLint and Prettier for code formatting.' },
      ],
    },
    {
      id: 'base-change-4',
      path: '/src/server/middleware/logging.ts',
      name: 'logging.ts',
      status: 'added',
      additions: 31,
      deletions: 0,
      diff: [
        { type: 'add', lineNumber: 1, content: 'import { Request, Response, NextFunction } from "express";' },
        { type: 'add', lineNumber: 2, content: '' },
        { type: 'add', lineNumber: 3, content: 'export function requestLogger(req: Request, res: Response, next: NextFunction) {' },
        { type: 'add', lineNumber: 4, content: '  const start = Date.now();' },
        { type: 'add', lineNumber: 5, content: '  res.on("finish", () => {' },
        { type: 'add', lineNumber: 6, content: '    const duration = Date.now() - start;' },
        { type: 'add', lineNumber: 7, content: '    console.log(`${req.method} ${req.path} ${res.statusCode} ${duration}ms`);' },
        { type: 'add', lineNumber: 8, content: '  });' },
        { type: 'add', lineNumber: 9, content: '  next();' },
        { type: 'add', lineNumber: 10, content: '}' },
      ],
    },
  ],
};